import Footer from "@/components/footer";
import Navbar from "components/navbar/Navbar"
import Head from "next/head";

const Layout = ({ children }) => {
  return (
    <>
     <Head>
      <link rel="preconnect" href="https://fonts.googleapis.com"/><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin /><link href="https://fonts.googleapis.com/css2?family=Mulish:ital,wght@0,200;0,300;0,400;0,500;0,700;0,800;0,900;0,1000;1,200;1,600;1,700;1,800;1,900&family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,500&display=swap" rel="stylesheet" />
        <title>Zero Waste Community Sharing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

     <Navbar />
      <main>{children}</main>
      <Footer/>
      
      
    </>
  );
};

export default Layout;



